apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: deploy
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp-container
          image: linuxacademycontent/store-products:1.0.0
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: front-end
