apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: myapp-container
      image: linuxacademycontent/store-products:1.0.0
      ports:
        - containerPort: 80