apiVersion: v1
kind: Service
metadata:
  name: myapp-node-port-service
  labels:
    name: nodeport-service
    app: myapp
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32321
  selector:
    name: deploy
    app: myapp